services:
  db:
      image: mariadb:latest
      container_name: ${NAMESPACE}_db
      working_dir: /app
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: password
        MARIADB_DATABASE: ${NAMESPACE}_db
        MARIADB_USER: ${NAMESPACE}
        MARIADB_PASSWORD: password
      volumes:
        - mariadb_data:/var/lib/mysql
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
      networks:
        - sunday-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}_app
    working_dir: /app
    restart: always
    environment:
      - APP_ENV=${APP_ENV:-development}
    volumes:
      - ../:/app
    command: >
      /bin/bash -c "
        if [[ \${APP_ENV} == 'production' || \${APP_ENV} == 'staging' ]]; then
          echo 'Using APP_ENV=${APP_ENV}';
          echo 'Installing project dependencies ...';
          bun install;
          echo 'Building production ready environment ...';
          bun run build;
          echo 'Starting the server ...';
          bun run start;
        else
          echo 'Using APP_ENV=development';
          echo 'Installing project dependencies ...';
          bun install;
          echo 'Running dev environment ...';
          bun run dev;
        fi
      "
    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - sunday-network

volumes:
  mariadb_data:

networks:
  sunday-network:
    name: sunday-network